name: "Daily flake update"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  nix-flake-update:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "chore: update flake"
          pr-labels: | # Labels to be set on the PR
            dependencies
            automated
          inputs: 
            nixpkgs
            nixpkgs-unstable
            home-manager
            nixCats
            nix-jetbrains-plugins
            hyprland
            hyprland-plugins
            hyprgrass
            caelestia-shell
            hm-unstable
            quickshell
            zen-browser
            apple-fonts
            catppuccin
            apple-silicon
